--NOMBRE FICHERO: 20111065013003201900.01
SELECT RUCCOOP||'|'||TIPODOCUMENTO||'|'||NUMERODOCUMENTO||'|'||APELLIDOPATERNO||'|'||APELLIDOMATERNO||'|'||NOMBRESOCIO||'|'||RAZONSOCIAL||'|'||CODTIPOPRESTAMO||'|'||FECHAPRESTAMO||'|'||MONEDA||'|'||MONTOPRESTAMO||'|'||AMORTIZACIONTOTAL||'|'||INTERESTOTAL||'|'||ANOINFORMADO AS CONCATENADO
FROM
(
    SELECT 
        '20111065013' AS RUCCOOP,   --RUCCOOP
        CASE TIPOPERSONA
            WHEN 1 THEN --NATURAL
                CASE PKG_PERSONANATURAL.F_OBT_TIPODOCUMENTOID(CODIGOPERSONA)
                    WHEN 1 THEN --DNI
                        '01'
                    WHEN 4 THEN --CARNET EXTRANJERIA
                        '04'
                    WHEN 5 THEN --PERMISO PROVISIONAL
                        '08'
                    WHEN 7 THEN --PASAPORTE
                        '07'
                    WHEN 8 THEN --DNI
                        '01'
                    ELSE        --OTRO
                        '09'
                END
            WHEN 2 THEN --JURIDICA
                '06'
        END AS TIPODOCUMENTO,       --TIPODOCUMENTO

        CASE TIPOPERSONA
            WHEN 1 THEN --NATURAL
                LPAD(PKG_PERSONANATURAL.F_OBT_NUMERODOCUMENTOID(CODIGOPERSONA), 15, ' ')
            WHEN 2 THEN --JURIDICA
                LPAD(PKG_PERSONA.F_OBT_NUMERORUC(CODIGOPERSONA), 15, ' ')
        END AS NUMERODOCUMENTO,     --NUMERODOCUMENTO
        CASE TIPOPERSONA
            WHEN 1 THEN --NATURAL
                LPAD(PKG_PERSONANATURAL.F_OBT_APELLIDOPATERNO(CODIGOPERSONA), 50, ' ')
            WHEN 2 THEN --JURIDICA
                ''--LPAD(' ', 50, ' ')
        END AS APELLIDOPATERNO,     --APELLIDOPATERNO
        CASE TIPOPERSONA
            WHEN 1 THEN --NATURAL
                LPAD(PKG_PERSONANATURAL.F_OBT_APELLIDOMATERNO(CODIGOPERSONA), 50, ' ')
            WHEN 2 THEN --JURIDICA
                ''--LPAD(' ', 50, ' ')
        END AS APELLIDOMATERNO,     --APELLIDOMATERNO
        CASE TIPOPERSONA
            WHEN 1 THEN --NATURAL
                LPAD(PKG_PERSONANATURAL.F_OBT_NOMBRES(CODIGOPERSONA), 80, ' ')
            WHEN 2 THEN --JURIDICA
                ''--LPAD(' ', 80, ' ')
        END AS NOMBRESOCIO,         --NOMBRESOCIO
        CASE TIPOPERSONA
            WHEN 1 THEN --NATURAL
                ''--LPAD(' ', 100, ' ')
            WHEN 2 THEN --JURIDICA
                LPAD(REPLACE(REPLACE(REPLACE(PKG_PERSONA.F_OBT_NOMBRECOMPLETO(CODIGOPERSONA), '''',''),' & ', ' Y '),'&', ' Y ') , 100, ' ')
        END AS RAZONSOCIAL,         --RAZONSOCIAL
        CASE TIPOPRESTAMO -- TCA5_Desc
            WHEN 'PEQUEÑAS EMPRESAS'
                THEN '04'
            WHEN 'HIPOTECARIO'
                THEN '08'
            WHEN 'MICROEMPRESAS'
                THEN '05'
            WHEN 'CONSUMO NO REVOLVENTE'
                THEN '07'
            WHEN 'MEDIANAS EMPRESAS'
                THEN '03'
            WHEN 'GRANDES EMPRESAS'
                THEN '02'
            ELSE
                '09'
        END AS CODTIPOPRESTAMO,
        FECHAPRESTAMO,
        CASE MONEDA
            WHEN 1
                THEN '01'
            WHEN 2
                THEN '02'
            ELSE
                '04'
        END AS MONEDA,

        CASE MONEDA
            WHEN 1
                THEN LPAD(TO_CHAR(MONTOPRESTAMO,'FM9999990.90'), 15)
            WHEN 2
                THEN LPAD(TO_CHAR(ROUND(MONTOPRESTAMO * GEN05200('31/12/2019', 3, 3), 2),'FM9999990.90'), 15)
        END MONTOPRESTAMO,

        CASE MONEDA
            WHEN 1
                THEN LPAD(TO_CHAR((MONTOPRESTAMO - SALDOPRESTAMO),'FM9999990.90'), 15)
            WHEN 2
                THEN LPAD(TO_CHAR(ROUND((MONTOPRESTAMO - SALDOPRESTAMO) * GEN05200('31/12/2019', 3, 3), 2),'FM9999990.90'), 15)
        END AMORTIZACIONTOTAL,

        CASE MONEDA
            WHEN 1
                THEN LPAD(TO_CHAR(INTERESTOTAL,'FM9999990.90'), 15)
            WHEN 2
                THEN LPAD(TO_CHAR(ROUND(INTERESTOTAL * GEN05200('31/12/2019', 3, 3), 2),'FM9999990.90'), 15)
        END INTERESTOTAL,
        '2019' AS ANOINFORMADO      --ANOINFORMADO
    FROM
    (
        SELECT 
            P.CODIGOPERSONA,
            PKG_PERSONA.F_OBT_TIPOPERSONA(CODIGOPERSONA) AS TIPOPERSONA,
            PKG_SYST900.F_OBT_TBLDESCRI(971, PKG_SOLICITUDPRESTAMO.F_OBT_TIPOSOLICITUD(P.PERIODOSOLICITUD, P.NUMEROSOLICITUD)) AS TIPOPRESTAMO,
            TO_CHAR(P.FECHAPRESTAMO, 'DD/MM/YYYY') AS FECHAPRESTAMO,
            P.MONEDA,
            P.MONTOPRESTAMO,
            P.SALDOPRESTAMO,
            SUM(INTERES) AS INTERESTOTAL
        FROM PRESTAMO P
        LEFT JOIN PRESTAMOPAGOS PP
        ON P.NUMEROSOLICITUD = PP.NUMEROSOLICITUD AND P.PERIODOSOLICITUD = PP.PERIODOSOLICITUD
        WHERE TO_CHAR(P.FECHAPRESTAMO,'YYYY') = 2019
            AND P.ESTADO < 3
            AND PP.ESTADO = 1
            AND P.PERIODOSOLICITUD <> 1
        GROUP BY P.CODIGOPERSONA, P.PERIODOSOLICITUD, P.NUMEROSOLICITUD, P.FECHAPRESTAMO, P.MONEDA, P.MONTOPRESTAMO, P.SALDOPRESTAMO
    )
);