--NOMBRE FICHERO: 20111065013003201900.01
--00:01
/*SELECT  RUCCOOP||'|'||
        TIPODOCUMENTO||'|'||
        RPAD(NVL(NUMERODOCUMENTO, ' '), 15, ' ')||'|'||
        RPAD(NVL(APELLIDOPATERNO, ' '), 50, ' ')||'|'||
        RPAD(NVL(APELLIDOMATERNO, ' '), 50, ' ')||'|'||
        RPAD(NVL(NOMBRESOCIO, ' '), 80, ' ')||'|'||
        RPAD(NVL(RAZONSOCIAL, ' '), 100, ' ')||'|'||
        CODTIPOPRESTAMO||'|'||
        TO_CHAR(MAX(FECHAPROGRAMACION), 'DD/MM/YYYY')||'|'||
        MONEDA||'|'||
        LPAD(TO_CHAR(SUM(MONTOPRESTSOLES), '999999990.99'), 15, ' ')||'|'||
        LPAD(TO_CHAR(
                        MAX(AMORTIZACIONSOLES) --Iguales
                    , '999999990.99')
            , 15, ' ')||'|'||
        LPAD(TO_CHAR(
                        MAX(INTERESSOLES) --Iguales
                    , '999999990.99')
            , 15, ' ')||'|'||
        ANOINFORMADO
        AS CONCATENADO
        --,PKG_PRESTAMO.F_OBT_CODIGOPERSONA(PERIODOSOLICITUD, NUMEROSOLICITUD)
FROM
(*/
    SELECT 
        '20111065013' AS RUCCOOP,   --RUCCOOP
        CASE TIPOPERSONA
            WHEN 1 THEN --NATURAL
                CASE PKG_PERSONANATURAL.F_OBT_TIPODOCUMENTOID(CODIGOPERSONA)
                    WHEN 1 THEN --DNI
                        '01'
                    WHEN 4 THEN --CARNET EXTRANJERIA
                        '04'
                    WHEN 5 THEN --PERMISO PROVISIONAL
                        '08'
                    WHEN 7 THEN --PASAPORTE
                        '07'
                    WHEN 8 THEN --DNI
                        '01'
                    ELSE        --OTRO
                        '09'
                END
            WHEN 2 THEN --JURIDICA
                '06'
        END AS TIPODOCUMENTO,       --TIPODOCUMENTO

        CASE TIPOPERSONA
            WHEN 1 THEN --NATURAL
                PKG_PERSONANATURAL.F_OBT_NUMERODOCUMENTOID(CODIGOPERSONA)
            WHEN 2 THEN --JURIDICA
                TO_CHAR(PKG_PERSONA.F_OBT_NUMERORUC(CODIGOPERSONA))
        END AS NUMERODOCUMENTO,     --NUMERODOCUMENTO
        CASE TIPOPERSONA
            WHEN 1 THEN --NATURAL
                PKG_PERSONANATURAL.F_OBT_APELLIDOPATERNO(CODIGOPERSONA)
            WHEN 2 THEN --JURIDICA
                ' '
        END AS APELLIDOPATERNO,     --APELLIDOPATERNO
        CASE TIPOPERSONA
            WHEN 1 THEN --NATURAL
                PKG_PERSONANATURAL.F_OBT_APELLIDOMATERNO(CODIGOPERSONA)
            WHEN 2 THEN --JURIDICA
                ' '
        END AS APELLIDOMATERNO,     --APELLIDOMATERNO
        CASE TIPOPERSONA
            WHEN 1 THEN --NATURAL
                PKG_PERSONANATURAL.F_OBT_NOMBRES(CODIGOPERSONA)
            WHEN 2 THEN --JURIDICA
                ' '--LPAD(' ', 80, ' ')
        END AS NOMBRESOCIO,         --NOMBRESOCIO
        CASE TIPOPERSONA
            WHEN 1 THEN --NATURAL
                ' '--LPAD(' ', 100, ' ')
            WHEN 2 THEN --JURIDICA
                REPLACE(REPLACE(REPLACE(PKG_PERSONA.F_OBT_NOMBRECOMPLETO(CODIGOPERSONA), '''',''),' & ', ' Y '),'&', ' Y ')
        END AS RAZONSOCIAL,         --RAZONSOCIAL
        CASE PKG_SYST900.F_OBT_TBLDESCRI(971, TIPOSOLICITUD) -- TCA5_Desc
            WHEN 'PEQUEÑAS EMPRESAS'
                THEN '04'
            WHEN 'HIPOTECARIO'
                THEN '08'
            WHEN 'MICROEMPRESAS'
                THEN '05'
            WHEN 'CONSUMO NO REVOLVENTE'
                THEN '07'
            WHEN 'MEDIANAS EMPRESAS'
                THEN '03'
            WHEN 'GRANDES EMPRESAS'
                THEN '02'
            ELSE
                '09'
        END AS CODTIPOPRESTAMO,
        TIPOPRESTAMO,
        FECHAPROGRAMACION,
        CASE MONEDA
            WHEN 1
                THEN '01'
            WHEN 2
                THEN '02'
            ELSE
                '04'
        END AS MONEDA,
        MONTOPRESTSOLES,
        AMORTIZACIONSOLES,
        INTERESSOLES,
        SUBSTR(PKG_SYST902.F_OBT_TBLDESCRI(TIPOSOLICITUD, TIPOPRESTAMO), 1, 3) AS PRODUCTO,
        PKG_SYST902.F_OBT_TBLDESCRI (0, TIPOSOLICITUD) AS TIPOPREST,
        PERIODOSOLICITUD,
        NUMEROSOLICITUD,
        '2019' AS ANOINFORMADO      --ANOINFORMADO
    FROM
    (
        SELECT 
        'CREDITOS' AS CAMPO,
        P.CODIGOPERSONA,
        PKG_PERSONA.F_OBT_TIPOPERSONA(P.CODIGOPERSONA) AS TIPOPERSONA,
        P.FECHAPROGRAMACION,
        P.MONEDA,
        CASE
            WHEN P.MONEDA = 1
                THEN NVL(P.MONTOPRESTAMO, 0)
                ELSE NVL(P.MONTOPRESTAMO, 0) * GEN05200('31/12/2019', 3, 3)
        END AS MONTOPRESTSOLES,

        (SELECT NVL(SUM(AMORTIZACION), 0) * (CASE
                                                        WHEN P.MONEDA = 1
                                                            THEN 1
                                                            ELSE GEN05200('31/12/2019', 3, 3)
                                                    END)
            FROM PRESTAMOPAGOS PP
            WHERE PP.PERIODOSOLICITUD = SP.PERIODOSOLICITUD
                AND PP.NUMEROSOLICITUD = SP.NUMEROSOLICITUD
                AND PP.ESTADO = 1
                AND TRUNC(FECHADEPOSITO) <= '31/12/2019')
            AS AMORTIZACIONSOLES,

        (SELECT NVL(SUM(INTERES), 0)
            FROM PRESTAMOPAGOS PP
            WHERE PP.PERIODOSOLICITUD = SP.PERIODOSOLICITUD
                AND PP.NUMEROSOLICITUD = SP.NUMEROSOLICITUD
                AND PP.ESTADO = 1
                AND TRUNC(FECHADEPOSITO) <= '31/12/2019')
            AS INTERESSOLES,
            
            SP.TIPOSOLICITUD,
            SP.TIPOPRESTAMO,
            P.PERIODOSOLICITUD,
            P.NUMEROSOLICITUD,
            P.MONTOPRESTAMO

        FROM PRESTAMO P
        INNER JOIN SOLICITUDPRESTAMO SP ON P.PERIODOSOLICITUD = SP.PERIODOSOLICITUD AND P.NUMEROSOLICITUD = SP.NUMEROSOLICITUD
        AND P.PERIODOSOLICITUD <> 1
        AND P.PERIODOSOLICITUDCONCESIONAL IS NULL AND P.NUMEROSOLICITUDCONCESIONAL IS NULL
        AND NVL(P.NUMEROLINEA, 0) < 2 AND NVL(P.PAGAREANTERIOR,' ') <> 'R'
        AND SUBSTR(PKG_SYST902.F_OBT_TBLDESCRI(TIPOSOLICITUD, TIPOPRESTAMO), 1, 3) <> 'PDD'
        AND SUBSTR(PKG_SYST902.F_OBT_TBLDESCRI(TIPOSOLICITUD, TIPOPRESTAMO), 1, 3) <> 'PLC'
        AND SUBSTR(PKG_SYST902.F_OBT_TBLDESCRI(TIPOSOLICITUD, TIPOPRESTAMO), 1, 3) <> 'PLR'
        WHERE TO_CHAR(P.FECHAPROGRAMACION, 'YYYY') = '2019'
            AND P.ESTADO < 3

        UNION ALL

        SELECT
                'INCREMENTO PLC' AS CAMPO,
                P.CODIGOPERSONA,
                PKG_PERSONA.F_OBT_TIPOPERSONA(P.CODIGOPERSONA) AS TIPOPERSONA,
                P.FECHAPROGRAMACION,
                P.MONEDA,
                SP.MONTOSOLICITADO * (CASE
                                                        WHEN P.MONEDA = 1
                                                            THEN 1
                                                            ELSE GEN05200('31/12/2019', 3, 3)
                                                    END)
                AS MONTOPRESTSOLES,
                (SELECT SUM(AMORTIZACION) * (CASE WHEN P.MONEDA = 1 THEN 1 ELSE GEN05200('31/12/2019', 3, 3) END) FROM PRESTAMOPAGOS PP2 WHERE PP2.PERIODOSOLICITUD = SP.PERIODOSOLICITUD AND PP2.NUMEROSOLICITUD = SP.NUMEROSOLICITUD AND PP2.ESTADO = 1 AND TO_CHAR(FECHADEPOSITO, 'YYYY') = '2019' GROUP BY PP2.PERIODOSOLICITUD, PP2.NUMEROSOLICITUD) AS AMORTIZACIONSOLES,
                (SELECT SUM(INTERES) * (CASE WHEN P.MONEDA = 1 THEN 1 ELSE GEN05200('31/12/2019', 3, 3) END) FROM PRESTAMOPAGOS PP2 WHERE PP2.PERIODOSOLICITUD = SP.PERIODOSOLICITUD AND PP2.NUMEROSOLICITUD = SP.NUMEROSOLICITUD AND PP2.ESTADO = 1 AND TO_CHAR(FECHADEPOSITO, 'YYYY') = '2019' GROUP BY PP2.PERIODOSOLICITUD, PP2.NUMEROSOLICITUD) AS INTERESSOLES,

                SP.TIPOSOLICITUD,
                SP.TIPOPRESTAMO,
                SP.PERIODOSOLICITUDCONCESIONAL,
                SP.NUMEROSOLICITUDCONCESIONAL,
                P.MONTOPRESTAMO AS MONTOPRESTAMO

        FROM PRESTAMO P
            INNER JOIN SOLICITUDPRESTAMO SP
                ON P.PERIODOSOLICITUD = SP.PERIODOSOLICITUD
                    AND P.NUMEROSOLICITUD = SP.NUMEROSOLICITUD
            AND SP.PERIODOSOLICITUDCONCESIONAL IS NOT NULL AND SP.NUMEROSOLICITUDCONCESIONAL IS NOT NULL
            WHERE TO_CHAR(P.FECHAPROGRAMACION, 'YYYY') = '2019'
                AND P.PERIODOSOLICITUD <> 1
                AND NVL(P.NUMEROLINEA, 0) < 2
                AND NVL(P.PAGAREANTERIOR, ' ') <> 'R'
                AND P.ESTADO < 3

        UNION ALL

        SELECT  'INCREMENTO PDD' AS CAMPO,
                P.CODIGOPERSONA,
                PKG_PERSONA.F_OBT_TIPOPERSONA(P.CODIGOPERSONA) AS TIPOPERSONA,
                PP.FECHADEPOSITO AS FECHADEPOSITO,
                P.MONEDA,
                AMORTIZACION * (CASE
                                                                                WHEN P.MONEDA = 1
                                                                                    THEN 1
                                                                                    ELSE GEN05200('31/12/2019', 3, 3)
                                                                            END)
                AS MONTOPRESTADOSOLES,
                (SELECT SUM(AMORTIZACION) * (CASE WHEN P.MONEDA = 1 THEN 1 ELSE GEN05200('31/12/2019', 3, 3) END) FROM PRESTAMOPAGOS PP2 WHERE PP2.PERIODOSOLICITUD = SP.PERIODOSOLICITUD AND PP2.NUMEROSOLICITUD = SP.NUMEROSOLICITUD AND PP2.ESTADO = 1 AND TO_CHAR(FECHADEPOSITO, 'YYYY') = '2019' GROUP BY PP2.PERIODOSOLICITUD, PP2.NUMEROSOLICITUD) AS AMORTIZACIONSOLES,
                (SELECT SUM(INTERES) * (CASE WHEN P.MONEDA = 1 THEN 1 ELSE GEN05200('31/12/2019', 3, 3) END) FROM PRESTAMOPAGOS PP2 WHERE PP2.PERIODOSOLICITUD = SP.PERIODOSOLICITUD AND PP2.NUMEROSOLICITUD = SP.NUMEROSOLICITUD AND PP2.ESTADO = 1 AND TO_CHAR(FECHADEPOSITO, 'YYYY') = '2019' GROUP BY PP2.PERIODOSOLICITUD, PP2.NUMEROSOLICITUD) AS INTERESSOLES,

                SP.TIPOSOLICITUD,
                SP.TIPOPRESTAMO,
                PP.PERIODOSOLICITUD,
                PP.NUMEROSOLICITUD,
                AMORTIZACION AS MONTOPRESTADO
        FROM PRESTAMOPAGOS PP
            LEFT JOIN SOLICITUDPRESTAMO SP
                ON PP.PERIODOSOLICITUD = SP.PERIODOSOLICITUD AND PP.NUMEROSOLICITUD = SP.NUMEROSOLICITUD
                LEFT JOIN PRESTAMO P
                    ON P.PERIODOSOLICITUD = SP.PERIODOSOLICITUD AND P.NUMEROSOLICITUD = SP.NUMEROSOLICITUD
        WHERE
        SUBSTR(PKG_SYST902.F_OBT_TBLDESCRI(TIPOSOLICITUD, TIPOPRESTAMO), 1, 3) = 'PDD'
        AND TO_CHAR(PP.FECHADEPOSITO, 'YYYY') = '2019'
        AND TIPOMOVIMIENTO = 4
        AND PP.ESTADO = 1
        AND PP.FECHAEXTORNO IS NULL
        AND PP.ITEMEXTORNADO IS NULL

        UNION ALL

        SELECT  'INCREMENTO PLR' AS CAMPO,
                P.CODIGOPERSONA,
                PKG_PERSONA.F_OBT_TIPOPERSONA(P.CODIGOPERSONA) AS TIPOPERSONA,
                PP.FECHADEPOSITO AS FECHADEPOSITO,
                P.MONEDA,
                AMORTIZACION * (CASE
                                                                                WHEN P.MONEDA = 1
                                                                                    THEN 1
                                                                                    ELSE GEN05200('31/12/2019', 3, 3)
                                                                            END)
                AS MONTOPRESTADOSOLES,
                (SELECT SUM(AMORTIZACION) * (CASE WHEN P.MONEDA = 1 THEN 1 ELSE GEN05200('31/12/2019', 3, 3) END) FROM PRESTAMOPAGOS PP2 WHERE PP2.PERIODOSOLICITUD = SP.PERIODOSOLICITUD AND PP2.NUMEROSOLICITUD = SP.NUMEROSOLICITUD AND PP2.ESTADO = 1 AND TO_CHAR(FECHADEPOSITO, 'YYYY') = '2019' GROUP BY PP2.PERIODOSOLICITUD, PP2.NUMEROSOLICITUD) AS AMORTIZACIONSOLES,
                (SELECT SUM(INTERES) * (CASE WHEN P.MONEDA = 1 THEN 1 ELSE GEN05200('31/12/2019', 3, 3) END) FROM PRESTAMOPAGOS PP2 WHERE PP2.PERIODOSOLICITUD = SP.PERIODOSOLICITUD AND PP2.NUMEROSOLICITUD = SP.NUMEROSOLICITUD AND PP2.ESTADO = 1 AND TO_CHAR(FECHADEPOSITO, 'YYYY') = '2019' GROUP BY PP2.PERIODOSOLICITUD, PP2.NUMEROSOLICITUD) AS INTERESSOLES,
                SP.TIPOSOLICITUD,
                SP.TIPOPRESTAMO,
                PP.PERIODOSOLICITUD,
                PP.NUMEROSOLICITUD,
                AMORTIZACION AS MONTOPRESTADO
        FROM PRESTAMOPAGOS PP
            LEFT JOIN SOLICITUDPRESTAMO SP
                ON PP.PERIODOSOLICITUD = SP.PERIODOSOLICITUD AND PP.NUMEROSOLICITUD = SP.NUMEROSOLICITUD
                LEFT JOIN PRESTAMO P
                    ON P.PERIODOSOLICITUD = SP.PERIODOSOLICITUD AND P.NUMEROSOLICITUD = SP.NUMEROSOLICITUD
        WHERE 
        SUBSTR(PKG_SYST902.F_OBT_TBLDESCRI(TIPOSOLICITUD, TIPOPRESTAMO), 1, 3) = 'PLR'
        AND TO_CHAR(PP.FECHADEPOSITO, 'YYYY') = '2019'
        AND TIPOMOVIMIENTO = 4
        AND PP.ESTADO = 1
        AND PP.FECHAEXTORNO IS NULL
        AND PP.ITEMEXTORNADO IS NULL
    )
/*)
GROUP BY RUCCOOP, TIPODOCUMENTO, NUMERODOCUMENTO, APELLIDOPATERNO, APELLIDOMATERNO, NOMBRESOCIO, RAZONSOCIAL, CODTIPOPRESTAMO, MONEDA, ANOINFORMADO, PERIODOSOLICITUD, NUMEROSOLICITUD
*/
;